name: seaice_radiative_transfer
channels:
 - conda-forge
dependencies:
 - python ~=3.10

  ################################################################
  # Imported dependencies and extensions (and related typestubs) #
  ################################################################

 - libgfortran ~= 3.0
 - jupyterlab
 - numpy ~= 1.24
 - pandas ~=1.52

 # To add
 # pandas 1.52
 #and matplotlib, pytest